# 生产环境配置文件
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/nutoj
    username: root
    password: oj.314159
  # Redis 配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
    password: oj.314159
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: guest
    username: guest
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
knife4j:
  enable: true
  production: true